<?php

namespace BayesPHP;

require_once dirname(__FILE__) . '/../BayesPHP/Classifier.php';

/**
 * Test class for Classifier.
 * Generated by PHPUnit on 2011-05-25 at 15:37:24.
 */
class ClassifierTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Classifier
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    public function testConstruct()
    {
        
    }

}

?>
