<?php

namespace BayesPHP;

require_once dirname(__FILE__) . '/../BayesPHP/Autoloader.php';
require_once dirname(__FILE__) . '/../BayesPHP/Sample.php';

/**
 * Test class for Sample.
 * Generated by PHPUnit on 2011-05-25 at 15:51:41.
 */
class SampleTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Sample
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $autoloader = new \BayesPHP\Autoloader('BayesPHP', __dir__ . '/..');
        $autoloader->register();
        $this->object = new Sample;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    public function testSetSampleUsingCorrectFormat()
    {
        
    }

    /**
     * @expectedException \BayesPHP\Exception\BadArgument
     */
    public function testSetSampleUsingIncorrectFormat()
    {
        $sample = array('x' => array(), 'z' => array());
        $this->object->setSample($sample);
    }

    public function testGetWordProbabilites()
    {
        $sample = array('p' => array(), 'n' => array());

        $sample = new Sample($sample, new WordCounter());
    }

}

?>
